from typing import Any, Dict, List, Union, Tuple

__version__: str
version: str

def bencode(data: Any) -> bytes: ...
def bdecode(data: bytes) -> Dict[bytes, Any]: ...
def add_files(fs: "file_storage", path: str) -> None: ...
def create_torrent(fs: "file_storage") -> "CreateTorrent": ...
def set_piece_hashes(t: "CreateTorrent", path: str, callback: Any = None) -> None: ...
def torrent_info(
    path_or_data: Union[str, Dict[Any, Any], bytes],
) -> "torrent_info_cls": ...
def sha1_hash(data: bytes) -> "sha1_hash_cls": ...

class sha1_hash_cls: ...
class file_storage:
    def add_file(self, path: str, size: int) -> None: ...

class CreateTorrent:
    def set_creator(self, creator: str) -> None: ...
    def set_comment(self, comment: str) -> None: ...
    def generate(self) -> Dict[str, Any]: ...

class torrent_info_cls:
    def info_hash(self) -> "sha1_hash_cls": ...

class session:
    def __init__(self, settings: Dict[str, Any] = ...) -> None: ...
    def pause(self) -> None: ...
    def stop(self) -> None: ...
    def save_state(self) -> bytes: ...
    def load_state(self, data: bytes) -> None: ...
    def post_session_stats(self) -> None: ...
    def listen_port(self) -> int: ...
    def add_torrent(self, params: Dict[str, Any]) -> "torrent_handle": ...
    def remove_torrent(self, handle: "torrent_handle", options: int = 0) -> None: ...
    def pop_alerts(self) -> List["alert"]: ...
    def get_torrents(self) -> List["torrent_handle"]: ...
    def wait_for_alert(self, max_wait_ms: int) -> bool: ...

class torrent_handle:
    def status(self) -> "torrent_status": ...
    def connect_peer(self, peer: Tuple[str, int]) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def move_storage(self, path: str, flags: int = 0) -> None: ...
    def info_hash(self) -> "sha1_hash_cls": ...
    def need_save_resume_data(self) -> bool: ...
    def save_resume_data(self, flags: int = 0) -> None: ...

class torrent_status:
    is_seeding: bool
    state: str
    progress: float
    class states:
        names: Dict[int, str]

def write_resume_data(params: Dict[str, Any]) -> Dict[str, Any]: ...
def read_resume_data(data: bytes) -> Dict[str, Any]: ...

class error_code:
    def message(self) -> str: ...

class save_resume_flags_t:
    flush_disk_cache: int
    save_info_dict: int

class alert:
    class category_t:
        all_categories: int
        error_notification: int
        peer_notification: int
        port_mapping_notification: int
        storage_notification: int
        tracker_notification: int
        status_notification: int
        ip_block_notification: int
        performance_warning: int
        stats_notification: int
        session_log_notification: int
        torrent_log_notification: int
        peer_log_notification: int

    values: Dict[str, Any]
    info_hash: "sha1_hash_cls"
    handle: "torrent_handle"
    def what(self) -> str: ...
    def category(self) -> int: ...
    def message(self) -> str: ...

class save_resume_data_alert(alert):
    params: Dict[str, Any]

class torrent_flags:
    apply_ip_filter: int
    auto_managed: int
    default_dont_download: int
    default_flags: int
    disable_dht: int
    disable_lsd: int
    disable_pex: int
    duplicate_is_error: int
    no_verify_files: int
    override_trackers: int
    override_web_seeds: int
    paused: int
    seed_mode: int
    sequential_download: int
    share_mode: int
    stop_when_ready: int
    super_seeding: int
    update_subscribe: int
    upload_mode: int

class options_t:
    delete_files: int
